### ISSUE TITLE
Consider directly using the STAC Extensions template?

### ISSUE THREAD

**Issue by cholmes** [linz/stac#4]
Hey there, I see you just aligned with the the stac extensions template.

You might consider redoing this repo to directly 'use' the template, you click 'use this template' button in green on the [template repo](https://github.com/stac-extensions/template). The reason being that you then get the nice automated continuous integration scripts we put in. Namely that when you make a github 'release' it will automatically publish the JSON schemas. 

No problem if you don't want to, feel free to close this issue, but it's nice when you get to publishing the extension, as if you get it right all the STAC ecosystem validation tools will work with it.

I'm super psyched on this extension, and on LINZ joining STAC, I've long been a fan of the LINZ public data portals, and their early adoption of geopackage.

**Comment by dwsilk** [comment]
Thanks Chris - I guess we'll need to split this repo into multiple repos (multiple extensions) that each follow the template. Since we haven't used this to generate any STAC metadata for our historical imagery just yet, I'm keen to do that first to sanity check what we have here.

I should also note that LINZ is now using STAC (+ COGs!) for our [Basemaps](https://github.com/linz/basemaps), [Geostore](https://github.com/linz/geostore) and [Topo Processor](https://github.com/linz/topo-processor) products. No doubt we are looking to contribute to a healthy ecosystem for these open specifications and formats.

**Comment by cholmes** [comment]
> Thanks Chris - I guess we'll need to split this repo into multiple repos (multiple extensions) that each follow the template. Since we haven't used this to generate any STAC metadata for our historical imagery just yet, I'm keen to do that first to sanity check what we have here.

Cool, definitely makes sense to sanity check first. I think you could also just start with one extension, with different prefixes in it, that has one schema, and split them up over time. For the more generic ones it could be nice to get them into the main stac_extensions github org, so that others can reuse / contribute and we get to an interoperable set of aerial / historic imagery STAC fields.

> I should also note that LINZ is now using STAC (+ COGs!) for our Basemaps, Geostore and Topo Processor products. No doubt we are looking to contribute to a healthy ecosystem for these open specifications and formats.

Oh, that's awesome! If you do have any public-facing STAC Catalogs it'd be great if you could add them to https://stacindex.org/ I'm also hoping to eventually do a blog series highlighting all the various uses of STAC, and it'd be great to feature LINZ at some point.

**Comment by dwsilk** [comment]
That sounds like a great way forward, thanks!

We don't have any public-facing STAC Catalogs yet but we will add them when we do. The blog series sounds good too.
